//
//  Repositories+Dependencies.swift
//  BrewerieSniffer
//
//  Created by Martin Lukacs on 18/03/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the MVVM Xcode Templates
//

import Resolver

extension Resolver {

    public static func registerRepositories() {
        register { BreweryRepository() as BreweryRepositoryContract }.scope(.shared)
    }
}

